// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package BPF

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type ringbufferBufsT struct{ Buf [32768]uint8 }

type ringbufferContainerKey struct {
	PidNs uint32
	MntNs uint32
}

type ringbufferDefaultContext struct {
	Ts        uint64
	Ck        ringbufferContainerKey
	HostPpid  uint32
	HostPid   uint32
	Ppid      uint32
	Pid       uint32
	Uid       uint32
	SyscallId uint32
	EventType uint32
	_         [4]byte
	RetValue  int64
	Comm      [16]int8
}

type ringbufferFileOprationContext struct {
	Basic    ringbufferDefaultContext
	Dirname  [4096]int8
	Filename [256]int8
}

type ringbufferNetworkOprationContext struct {
	Basic    ringbufferDefaultContext
	DestIpv4 uint32
	DestPort uint16
	_        [2]byte
}

type ringbufferProcessManagementContext struct {
	Basic   ringbufferDefaultContext
	ExePath [256]int8
	Dirname [4096]int8
}

// loadRingbuffer returns the embedded CollectionSpec for ringbuffer.
func loadRingbuffer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RingbufferBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ringbuffer: %w", err)
	}

	return spec, err
}

// loadRingbufferObjects loads ringbuffer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ringbufferObjects
//	*ringbufferPrograms
//	*ringbufferMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRingbufferObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRingbuffer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ringbufferSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ringbufferSpecs struct {
	ringbufferProgramSpecs
	ringbufferMapSpecs
}

// ringbufferSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ringbufferProgramSpecs struct {
	KprobeX64SysAccept             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_accept"`
	KprobeX64SysBind               *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_bind"`
	KprobeX64SysBrk                *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_brk"`
	KprobeX64SysChown              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_chown"`
	KprobeX64SysClone              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_clone"`
	KprobeX64SysClose              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_close"`
	KprobeX64SysConnect            *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_connect"`
	KprobeX64SysDup                *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_dup"`
	KprobeX64SysDup2               *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_dup2"`
	KprobeX64SysDup3               *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_dup3"`
	KprobeX64SysExecve             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_execve"`
	KprobeX64SysExecveat           *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_execveat"`
	KprobeX64SysExit               *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_exit"`
	KprobeX64SysExitGroup          *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_exit_group"`
	KprobeX64SysFchownat           *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_fchownat"`
	KprobeX64SysFcntl              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_fcntl"`
	KprobeX64SysFdatasync          *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_fdatasync"`
	KprobeX64SysFork               *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_fork"`
	KprobeX64SysFstat              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_fstat"`
	KprobeX64SysFsync              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_fsync"`
	KprobeX64SysGetegid            *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_getegid"`
	KprobeX64SysGeteuid            *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_geteuid"`
	KprobeX64SysGetgid             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_getgid"`
	KprobeX64SysGetpid             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_getpid"`
	KprobeX64SysGetppid            *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_getppid"`
	KprobeX64SysGetrlimit          *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_getrlimit"`
	KprobeX64SysGetrusage          *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_getrusage"`
	KprobeX64SysGetuid             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_getuid"`
	KprobeX64SysKill               *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_kill"`
	KprobeX64SysListen             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_listen"`
	KprobeX64SysLseek              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_lseek"`
	KprobeX64SysLstat              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_lstat"`
	KprobeX64SysMadvise            *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_madvise"`
	KprobeX64SysMmap               *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_mmap"`
	KprobeX64SysMount              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_mount"`
	KprobeX64SysMprotect           *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_mprotect"`
	KprobeX64SysMunmap             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_munmap"`
	KprobeX64SysOpen               *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_open"`
	KprobeX64SysOpenat             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_openat"`
	KprobeX64SysPread64            *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_pread64"`
	KprobeX64SysPwrite64           *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_pwrite64"`
	KprobeX64SysRead               *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_read"`
	KprobeX64SysSetgid             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_setgid"`
	KprobeX64SysSetrlimit          *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_setrlimit"`
	KprobeX64SysSetuid             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_setuid"`
	KprobeX64SysSignal             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_signal"`
	KprobeX64SysSocket             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_socket"`
	KprobeX64SysStat               *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_stat"`
	KprobeX64SysSync               *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_sync"`
	KprobeX64SysTgkill             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_tgkill"`
	KprobeX64SysTimerCreate        *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_timer_create"`
	KprobeX64SysTimerDelete        *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_timer_delete"`
	KprobeX64SysTimerGetoverrun    *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_timer_getoverrun"`
	KprobeX64SysTimerGettime       *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_timer_gettime"`
	KprobeX64SysTimerSettime       *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_timer_settime"`
	KprobeX64SysTkill              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_tkill"`
	KprobeX64SysUmount             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_umount"`
	KprobeX64SysUname              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_uname"`
	KprobeX64SysUnlink             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_unlink"`
	KprobeX64SysUnlinkat           *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_unlinkat"`
	KprobeX64SysVfork              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_vfork"`
	KprobeX64SysWait4              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_wait4"`
	KprobeX64SysWaitid             *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_waitid"`
	KprobeX64SysWrite              *ebpf.ProgramSpec `ebpf:"kprobe___x64_sys_write"`
	KretprobeX64SysAccept          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_accept"`
	KretprobeX64SysBind            *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_bind"`
	KretprobeX64SysBrk             *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_brk"`
	KretprobeX64SysChown           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_chown"`
	KretprobeX64SysClone           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_clone"`
	KretprobeX64SysClose           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_close"`
	KretprobeX64SysConnect         *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_connect"`
	KretprobeX64SysDup             *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_dup"`
	KretprobeX64SysDup2            *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_dup2"`
	KretprobeX64SysDup3            *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_dup3"`
	KretprobeX64SysExecve          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_execve"`
	KretprobeX64SysExecveat        *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_execveat"`
	KretprobeX64SysExit            *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_exit"`
	KretprobeX64SysExitGroup       *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_exit_group"`
	KretprobeX64SysFchownat        *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_fchownat"`
	KretprobeX64SysFcntl           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_fcntl"`
	KretprobeX64SysFdatasync       *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_fdatasync"`
	KretprobeX64SysFork            *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_fork"`
	KretprobeX64SysFstat           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_fstat"`
	KretprobeX64SysFsync           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_fsync"`
	KretprobeX64SysGetegid         *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_getegid"`
	KretprobeX64SysGeteuid         *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_geteuid"`
	KretprobeX64SysGetgid          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_getgid"`
	KretprobeX64SysGetpid          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_getpid"`
	KretprobeX64SysGetppid         *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_getppid"`
	KretprobeX64SysGetrlimit       *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_getrlimit"`
	KretprobeX64SysGetrusage       *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_getrusage"`
	KretprobeX64SysGetuid          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_getuid"`
	KretprobeX64SysKill            *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_kill"`
	KretprobeX64SysListen          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_listen"`
	KretprobeX64SysLseek           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_lseek"`
	KretprobeX64SysLstat           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_lstat"`
	KretprobeX64SysMadvise         *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_madvise"`
	KretprobeX64SysMmap            *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_mmap"`
	KretprobeX64SysMount           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_mount"`
	KretprobeX64SysMprotect        *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_mprotect"`
	KretprobeX64SysMunmap          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_munmap"`
	KretprobeX64SysOpen            *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_open"`
	KretprobeX64SysOpenat          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_openat"`
	KretprobeX64SysPread64         *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_pread64"`
	KretprobeX64SysPwrite64        *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_pwrite64"`
	KretprobeX64SysRead            *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_read"`
	KretprobeX64SysSetgid          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_setgid"`
	KretprobeX64SysSetrlimit       *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_setrlimit"`
	KretprobeX64SysSetuid          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_setuid"`
	KretprobeX64SysSignal          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_signal"`
	KretprobeX64SysSocket          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_socket"`
	KretprobeX64SysStat            *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_stat"`
	KretprobeX64SysSync            *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_sync"`
	KretprobeX64SysTgkill          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_tgkill"`
	KretprobeX64SysTimerCreate     *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_timer_create"`
	KretprobeX64SysTimerDelete     *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_timer_delete"`
	KretprobeX64SysTimerGetoverrun *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_timer_getoverrun"`
	KretprobeX64SysTimerGettime    *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_timer_gettime"`
	KretprobeX64SysTimerSettime    *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_timer_settime"`
	KretprobeX64SysTkill           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_tkill"`
	KretprobeX64SysUmount          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_umount"`
	KretprobeX64SysUname           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_uname"`
	KretprobeX64SysUnlink          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_unlink"`
	KretprobeX64SysUnlinkat        *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_unlinkat"`
	KretprobeX64SysVfork           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_vfork"`
	KretprobeX64SysWait4           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_wait4"`
	KretprobeX64SysWaitid          *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_waitid"`
	KretprobeX64SysWrite           *ebpf.ProgramSpec `ebpf:"kretprobe___x64_sys_write"`
}

// ringbufferMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ringbufferMapSpecs struct {
	Bufs         *ebpf.MapSpec `ebpf:"bufs"`
	ContainerMap *ebpf.MapSpec `ebpf:"container_map"`
	KprobeMap    *ebpf.MapSpec `ebpf:"kprobe_map"`
	KretprobeMap *ebpf.MapSpec `ebpf:"kretprobe_map"`
}

// ringbufferObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRingbufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type ringbufferObjects struct {
	ringbufferPrograms
	ringbufferMaps
}

func (o *ringbufferObjects) Close() error {
	return _RingbufferClose(
		&o.ringbufferPrograms,
		&o.ringbufferMaps,
	)
}

// ringbufferMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRingbufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type ringbufferMaps struct {
	Bufs         *ebpf.Map `ebpf:"bufs"`
	ContainerMap *ebpf.Map `ebpf:"container_map"`
	KprobeMap    *ebpf.Map `ebpf:"kprobe_map"`
	KretprobeMap *ebpf.Map `ebpf:"kretprobe_map"`
}

func (m *ringbufferMaps) Close() error {
	return _RingbufferClose(
		m.Bufs,
		m.ContainerMap,
		m.KprobeMap,
		m.KretprobeMap,
	)
}

// ringbufferPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRingbufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type ringbufferPrograms struct {
	KprobeX64SysAccept             *ebpf.Program `ebpf:"kprobe___x64_sys_accept"`
	KprobeX64SysBind               *ebpf.Program `ebpf:"kprobe___x64_sys_bind"`
	KprobeX64SysBrk                *ebpf.Program `ebpf:"kprobe___x64_sys_brk"`
	KprobeX64SysChown              *ebpf.Program `ebpf:"kprobe___x64_sys_chown"`
	KprobeX64SysClone              *ebpf.Program `ebpf:"kprobe___x64_sys_clone"`
	KprobeX64SysClose              *ebpf.Program `ebpf:"kprobe___x64_sys_close"`
	KprobeX64SysConnect            *ebpf.Program `ebpf:"kprobe___x64_sys_connect"`
	KprobeX64SysDup                *ebpf.Program `ebpf:"kprobe___x64_sys_dup"`
	KprobeX64SysDup2               *ebpf.Program `ebpf:"kprobe___x64_sys_dup2"`
	KprobeX64SysDup3               *ebpf.Program `ebpf:"kprobe___x64_sys_dup3"`
	KprobeX64SysExecve             *ebpf.Program `ebpf:"kprobe___x64_sys_execve"`
	KprobeX64SysExecveat           *ebpf.Program `ebpf:"kprobe___x64_sys_execveat"`
	KprobeX64SysExit               *ebpf.Program `ebpf:"kprobe___x64_sys_exit"`
	KprobeX64SysExitGroup          *ebpf.Program `ebpf:"kprobe___x64_sys_exit_group"`
	KprobeX64SysFchownat           *ebpf.Program `ebpf:"kprobe___x64_sys_fchownat"`
	KprobeX64SysFcntl              *ebpf.Program `ebpf:"kprobe___x64_sys_fcntl"`
	KprobeX64SysFdatasync          *ebpf.Program `ebpf:"kprobe___x64_sys_fdatasync"`
	KprobeX64SysFork               *ebpf.Program `ebpf:"kprobe___x64_sys_fork"`
	KprobeX64SysFstat              *ebpf.Program `ebpf:"kprobe___x64_sys_fstat"`
	KprobeX64SysFsync              *ebpf.Program `ebpf:"kprobe___x64_sys_fsync"`
	KprobeX64SysGetegid            *ebpf.Program `ebpf:"kprobe___x64_sys_getegid"`
	KprobeX64SysGeteuid            *ebpf.Program `ebpf:"kprobe___x64_sys_geteuid"`
	KprobeX64SysGetgid             *ebpf.Program `ebpf:"kprobe___x64_sys_getgid"`
	KprobeX64SysGetpid             *ebpf.Program `ebpf:"kprobe___x64_sys_getpid"`
	KprobeX64SysGetppid            *ebpf.Program `ebpf:"kprobe___x64_sys_getppid"`
	KprobeX64SysGetrlimit          *ebpf.Program `ebpf:"kprobe___x64_sys_getrlimit"`
	KprobeX64SysGetrusage          *ebpf.Program `ebpf:"kprobe___x64_sys_getrusage"`
	KprobeX64SysGetuid             *ebpf.Program `ebpf:"kprobe___x64_sys_getuid"`
	KprobeX64SysKill               *ebpf.Program `ebpf:"kprobe___x64_sys_kill"`
	KprobeX64SysListen             *ebpf.Program `ebpf:"kprobe___x64_sys_listen"`
	KprobeX64SysLseek              *ebpf.Program `ebpf:"kprobe___x64_sys_lseek"`
	KprobeX64SysLstat              *ebpf.Program `ebpf:"kprobe___x64_sys_lstat"`
	KprobeX64SysMadvise            *ebpf.Program `ebpf:"kprobe___x64_sys_madvise"`
	KprobeX64SysMmap               *ebpf.Program `ebpf:"kprobe___x64_sys_mmap"`
	KprobeX64SysMount              *ebpf.Program `ebpf:"kprobe___x64_sys_mount"`
	KprobeX64SysMprotect           *ebpf.Program `ebpf:"kprobe___x64_sys_mprotect"`
	KprobeX64SysMunmap             *ebpf.Program `ebpf:"kprobe___x64_sys_munmap"`
	KprobeX64SysOpen               *ebpf.Program `ebpf:"kprobe___x64_sys_open"`
	KprobeX64SysOpenat             *ebpf.Program `ebpf:"kprobe___x64_sys_openat"`
	KprobeX64SysPread64            *ebpf.Program `ebpf:"kprobe___x64_sys_pread64"`
	KprobeX64SysPwrite64           *ebpf.Program `ebpf:"kprobe___x64_sys_pwrite64"`
	KprobeX64SysRead               *ebpf.Program `ebpf:"kprobe___x64_sys_read"`
	KprobeX64SysSetgid             *ebpf.Program `ebpf:"kprobe___x64_sys_setgid"`
	KprobeX64SysSetrlimit          *ebpf.Program `ebpf:"kprobe___x64_sys_setrlimit"`
	KprobeX64SysSetuid             *ebpf.Program `ebpf:"kprobe___x64_sys_setuid"`
	KprobeX64SysSignal             *ebpf.Program `ebpf:"kprobe___x64_sys_signal"`
	KprobeX64SysSocket             *ebpf.Program `ebpf:"kprobe___x64_sys_socket"`
	KprobeX64SysStat               *ebpf.Program `ebpf:"kprobe___x64_sys_stat"`
	KprobeX64SysSync               *ebpf.Program `ebpf:"kprobe___x64_sys_sync"`
	KprobeX64SysTgkill             *ebpf.Program `ebpf:"kprobe___x64_sys_tgkill"`
	KprobeX64SysTimerCreate        *ebpf.Program `ebpf:"kprobe___x64_sys_timer_create"`
	KprobeX64SysTimerDelete        *ebpf.Program `ebpf:"kprobe___x64_sys_timer_delete"`
	KprobeX64SysTimerGetoverrun    *ebpf.Program `ebpf:"kprobe___x64_sys_timer_getoverrun"`
	KprobeX64SysTimerGettime       *ebpf.Program `ebpf:"kprobe___x64_sys_timer_gettime"`
	KprobeX64SysTimerSettime       *ebpf.Program `ebpf:"kprobe___x64_sys_timer_settime"`
	KprobeX64SysTkill              *ebpf.Program `ebpf:"kprobe___x64_sys_tkill"`
	KprobeX64SysUmount             *ebpf.Program `ebpf:"kprobe___x64_sys_umount"`
	KprobeX64SysUname              *ebpf.Program `ebpf:"kprobe___x64_sys_uname"`
	KprobeX64SysUnlink             *ebpf.Program `ebpf:"kprobe___x64_sys_unlink"`
	KprobeX64SysUnlinkat           *ebpf.Program `ebpf:"kprobe___x64_sys_unlinkat"`
	KprobeX64SysVfork              *ebpf.Program `ebpf:"kprobe___x64_sys_vfork"`
	KprobeX64SysWait4              *ebpf.Program `ebpf:"kprobe___x64_sys_wait4"`
	KprobeX64SysWaitid             *ebpf.Program `ebpf:"kprobe___x64_sys_waitid"`
	KprobeX64SysWrite              *ebpf.Program `ebpf:"kprobe___x64_sys_write"`
	KretprobeX64SysAccept          *ebpf.Program `ebpf:"kretprobe___x64_sys_accept"`
	KretprobeX64SysBind            *ebpf.Program `ebpf:"kretprobe___x64_sys_bind"`
	KretprobeX64SysBrk             *ebpf.Program `ebpf:"kretprobe___x64_sys_brk"`
	KretprobeX64SysChown           *ebpf.Program `ebpf:"kretprobe___x64_sys_chown"`
	KretprobeX64SysClone           *ebpf.Program `ebpf:"kretprobe___x64_sys_clone"`
	KretprobeX64SysClose           *ebpf.Program `ebpf:"kretprobe___x64_sys_close"`
	KretprobeX64SysConnect         *ebpf.Program `ebpf:"kretprobe___x64_sys_connect"`
	KretprobeX64SysDup             *ebpf.Program `ebpf:"kretprobe___x64_sys_dup"`
	KretprobeX64SysDup2            *ebpf.Program `ebpf:"kretprobe___x64_sys_dup2"`
	KretprobeX64SysDup3            *ebpf.Program `ebpf:"kretprobe___x64_sys_dup3"`
	KretprobeX64SysExecve          *ebpf.Program `ebpf:"kretprobe___x64_sys_execve"`
	KretprobeX64SysExecveat        *ebpf.Program `ebpf:"kretprobe___x64_sys_execveat"`
	KretprobeX64SysExit            *ebpf.Program `ebpf:"kretprobe___x64_sys_exit"`
	KretprobeX64SysExitGroup       *ebpf.Program `ebpf:"kretprobe___x64_sys_exit_group"`
	KretprobeX64SysFchownat        *ebpf.Program `ebpf:"kretprobe___x64_sys_fchownat"`
	KretprobeX64SysFcntl           *ebpf.Program `ebpf:"kretprobe___x64_sys_fcntl"`
	KretprobeX64SysFdatasync       *ebpf.Program `ebpf:"kretprobe___x64_sys_fdatasync"`
	KretprobeX64SysFork            *ebpf.Program `ebpf:"kretprobe___x64_sys_fork"`
	KretprobeX64SysFstat           *ebpf.Program `ebpf:"kretprobe___x64_sys_fstat"`
	KretprobeX64SysFsync           *ebpf.Program `ebpf:"kretprobe___x64_sys_fsync"`
	KretprobeX64SysGetegid         *ebpf.Program `ebpf:"kretprobe___x64_sys_getegid"`
	KretprobeX64SysGeteuid         *ebpf.Program `ebpf:"kretprobe___x64_sys_geteuid"`
	KretprobeX64SysGetgid          *ebpf.Program `ebpf:"kretprobe___x64_sys_getgid"`
	KretprobeX64SysGetpid          *ebpf.Program `ebpf:"kretprobe___x64_sys_getpid"`
	KretprobeX64SysGetppid         *ebpf.Program `ebpf:"kretprobe___x64_sys_getppid"`
	KretprobeX64SysGetrlimit       *ebpf.Program `ebpf:"kretprobe___x64_sys_getrlimit"`
	KretprobeX64SysGetrusage       *ebpf.Program `ebpf:"kretprobe___x64_sys_getrusage"`
	KretprobeX64SysGetuid          *ebpf.Program `ebpf:"kretprobe___x64_sys_getuid"`
	KretprobeX64SysKill            *ebpf.Program `ebpf:"kretprobe___x64_sys_kill"`
	KretprobeX64SysListen          *ebpf.Program `ebpf:"kretprobe___x64_sys_listen"`
	KretprobeX64SysLseek           *ebpf.Program `ebpf:"kretprobe___x64_sys_lseek"`
	KretprobeX64SysLstat           *ebpf.Program `ebpf:"kretprobe___x64_sys_lstat"`
	KretprobeX64SysMadvise         *ebpf.Program `ebpf:"kretprobe___x64_sys_madvise"`
	KretprobeX64SysMmap            *ebpf.Program `ebpf:"kretprobe___x64_sys_mmap"`
	KretprobeX64SysMount           *ebpf.Program `ebpf:"kretprobe___x64_sys_mount"`
	KretprobeX64SysMprotect        *ebpf.Program `ebpf:"kretprobe___x64_sys_mprotect"`
	KretprobeX64SysMunmap          *ebpf.Program `ebpf:"kretprobe___x64_sys_munmap"`
	KretprobeX64SysOpen            *ebpf.Program `ebpf:"kretprobe___x64_sys_open"`
	KretprobeX64SysOpenat          *ebpf.Program `ebpf:"kretprobe___x64_sys_openat"`
	KretprobeX64SysPread64         *ebpf.Program `ebpf:"kretprobe___x64_sys_pread64"`
	KretprobeX64SysPwrite64        *ebpf.Program `ebpf:"kretprobe___x64_sys_pwrite64"`
	KretprobeX64SysRead            *ebpf.Program `ebpf:"kretprobe___x64_sys_read"`
	KretprobeX64SysSetgid          *ebpf.Program `ebpf:"kretprobe___x64_sys_setgid"`
	KretprobeX64SysSetrlimit       *ebpf.Program `ebpf:"kretprobe___x64_sys_setrlimit"`
	KretprobeX64SysSetuid          *ebpf.Program `ebpf:"kretprobe___x64_sys_setuid"`
	KretprobeX64SysSignal          *ebpf.Program `ebpf:"kretprobe___x64_sys_signal"`
	KretprobeX64SysSocket          *ebpf.Program `ebpf:"kretprobe___x64_sys_socket"`
	KretprobeX64SysStat            *ebpf.Program `ebpf:"kretprobe___x64_sys_stat"`
	KretprobeX64SysSync            *ebpf.Program `ebpf:"kretprobe___x64_sys_sync"`
	KretprobeX64SysTgkill          *ebpf.Program `ebpf:"kretprobe___x64_sys_tgkill"`
	KretprobeX64SysTimerCreate     *ebpf.Program `ebpf:"kretprobe___x64_sys_timer_create"`
	KretprobeX64SysTimerDelete     *ebpf.Program `ebpf:"kretprobe___x64_sys_timer_delete"`
	KretprobeX64SysTimerGetoverrun *ebpf.Program `ebpf:"kretprobe___x64_sys_timer_getoverrun"`
	KretprobeX64SysTimerGettime    *ebpf.Program `ebpf:"kretprobe___x64_sys_timer_gettime"`
	KretprobeX64SysTimerSettime    *ebpf.Program `ebpf:"kretprobe___x64_sys_timer_settime"`
	KretprobeX64SysTkill           *ebpf.Program `ebpf:"kretprobe___x64_sys_tkill"`
	KretprobeX64SysUmount          *ebpf.Program `ebpf:"kretprobe___x64_sys_umount"`
	KretprobeX64SysUname           *ebpf.Program `ebpf:"kretprobe___x64_sys_uname"`
	KretprobeX64SysUnlink          *ebpf.Program `ebpf:"kretprobe___x64_sys_unlink"`
	KretprobeX64SysUnlinkat        *ebpf.Program `ebpf:"kretprobe___x64_sys_unlinkat"`
	KretprobeX64SysVfork           *ebpf.Program `ebpf:"kretprobe___x64_sys_vfork"`
	KretprobeX64SysWait4           *ebpf.Program `ebpf:"kretprobe___x64_sys_wait4"`
	KretprobeX64SysWaitid          *ebpf.Program `ebpf:"kretprobe___x64_sys_waitid"`
	KretprobeX64SysWrite           *ebpf.Program `ebpf:"kretprobe___x64_sys_write"`
}

func (p *ringbufferPrograms) Close() error {
	return _RingbufferClose(
		p.KprobeX64SysAccept,
		p.KprobeX64SysBind,
		p.KprobeX64SysBrk,
		p.KprobeX64SysChown,
		p.KprobeX64SysClone,
		p.KprobeX64SysClose,
		p.KprobeX64SysConnect,
		p.KprobeX64SysDup,
		p.KprobeX64SysDup2,
		p.KprobeX64SysDup3,
		p.KprobeX64SysExecve,
		p.KprobeX64SysExecveat,
		p.KprobeX64SysExit,
		p.KprobeX64SysExitGroup,
		p.KprobeX64SysFchownat,
		p.KprobeX64SysFcntl,
		p.KprobeX64SysFdatasync,
		p.KprobeX64SysFork,
		p.KprobeX64SysFstat,
		p.KprobeX64SysFsync,
		p.KprobeX64SysGetegid,
		p.KprobeX64SysGeteuid,
		p.KprobeX64SysGetgid,
		p.KprobeX64SysGetpid,
		p.KprobeX64SysGetppid,
		p.KprobeX64SysGetrlimit,
		p.KprobeX64SysGetrusage,
		p.KprobeX64SysGetuid,
		p.KprobeX64SysKill,
		p.KprobeX64SysListen,
		p.KprobeX64SysLseek,
		p.KprobeX64SysLstat,
		p.KprobeX64SysMadvise,
		p.KprobeX64SysMmap,
		p.KprobeX64SysMount,
		p.KprobeX64SysMprotect,
		p.KprobeX64SysMunmap,
		p.KprobeX64SysOpen,
		p.KprobeX64SysOpenat,
		p.KprobeX64SysPread64,
		p.KprobeX64SysPwrite64,
		p.KprobeX64SysRead,
		p.KprobeX64SysSetgid,
		p.KprobeX64SysSetrlimit,
		p.KprobeX64SysSetuid,
		p.KprobeX64SysSignal,
		p.KprobeX64SysSocket,
		p.KprobeX64SysStat,
		p.KprobeX64SysSync,
		p.KprobeX64SysTgkill,
		p.KprobeX64SysTimerCreate,
		p.KprobeX64SysTimerDelete,
		p.KprobeX64SysTimerGetoverrun,
		p.KprobeX64SysTimerGettime,
		p.KprobeX64SysTimerSettime,
		p.KprobeX64SysTkill,
		p.KprobeX64SysUmount,
		p.KprobeX64SysUname,
		p.KprobeX64SysUnlink,
		p.KprobeX64SysUnlinkat,
		p.KprobeX64SysVfork,
		p.KprobeX64SysWait4,
		p.KprobeX64SysWaitid,
		p.KprobeX64SysWrite,
		p.KretprobeX64SysAccept,
		p.KretprobeX64SysBind,
		p.KretprobeX64SysBrk,
		p.KretprobeX64SysChown,
		p.KretprobeX64SysClone,
		p.KretprobeX64SysClose,
		p.KretprobeX64SysConnect,
		p.KretprobeX64SysDup,
		p.KretprobeX64SysDup2,
		p.KretprobeX64SysDup3,
		p.KretprobeX64SysExecve,
		p.KretprobeX64SysExecveat,
		p.KretprobeX64SysExit,
		p.KretprobeX64SysExitGroup,
		p.KretprobeX64SysFchownat,
		p.KretprobeX64SysFcntl,
		p.KretprobeX64SysFdatasync,
		p.KretprobeX64SysFork,
		p.KretprobeX64SysFstat,
		p.KretprobeX64SysFsync,
		p.KretprobeX64SysGetegid,
		p.KretprobeX64SysGeteuid,
		p.KretprobeX64SysGetgid,
		p.KretprobeX64SysGetpid,
		p.KretprobeX64SysGetppid,
		p.KretprobeX64SysGetrlimit,
		p.KretprobeX64SysGetrusage,
		p.KretprobeX64SysGetuid,
		p.KretprobeX64SysKill,
		p.KretprobeX64SysListen,
		p.KretprobeX64SysLseek,
		p.KretprobeX64SysLstat,
		p.KretprobeX64SysMadvise,
		p.KretprobeX64SysMmap,
		p.KretprobeX64SysMount,
		p.KretprobeX64SysMprotect,
		p.KretprobeX64SysMunmap,
		p.KretprobeX64SysOpen,
		p.KretprobeX64SysOpenat,
		p.KretprobeX64SysPread64,
		p.KretprobeX64SysPwrite64,
		p.KretprobeX64SysRead,
		p.KretprobeX64SysSetgid,
		p.KretprobeX64SysSetrlimit,
		p.KretprobeX64SysSetuid,
		p.KretprobeX64SysSignal,
		p.KretprobeX64SysSocket,
		p.KretprobeX64SysStat,
		p.KretprobeX64SysSync,
		p.KretprobeX64SysTgkill,
		p.KretprobeX64SysTimerCreate,
		p.KretprobeX64SysTimerDelete,
		p.KretprobeX64SysTimerGetoverrun,
		p.KretprobeX64SysTimerGettime,
		p.KretprobeX64SysTimerSettime,
		p.KretprobeX64SysTkill,
		p.KretprobeX64SysUmount,
		p.KretprobeX64SysUname,
		p.KretprobeX64SysUnlink,
		p.KretprobeX64SysUnlinkat,
		p.KretprobeX64SysVfork,
		p.KretprobeX64SysWait4,
		p.KretprobeX64SysWaitid,
		p.KretprobeX64SysWrite,
	)
}

func _RingbufferClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ringbuffer_bpfel_x86.o
var _RingbufferBytes []byte
